- name: Clone keylime
  git:
    repo: https://github.com/keylime/keylime
    dest: /root/keylime

- name: Run python setup tools to install Keylime
  command: python2.7 setup.py install
  args:
    chdir: /root/keylime
